"""Studio 在共享 Redis 中使用的业务键前缀"""

_STUDIO_REDIS_PREFIX = "tinkerfin:studio"

AUTH_TOKEN_KEY_PREFIX = f"{_STUDIO_REDIS_PREFIX}:auth"
MESSAGING_KEY_PREFIX = f"{_STUDIO_REDIS_PREFIX}:messaging"
NOTIFICATIONS_CHANNEL = f"{_STUDIO_REDIS_PREFIX}:notifications"
CHECKPOINT_KEY_PREFIX = f"{_STUDIO_REDIS_PREFIX}:checkpoint"
CHECKPOINT_WRITE_KEY_PREFIX = f"{_STUDIO_REDIS_PREFIX}:checkpoint_write"

__all__ = [
    "AUTH_TOKEN_KEY_PREFIX",
    "CHECKPOINT_KEY_PREFIX",
    "CHECKPOINT_WRITE_KEY_PREFIX",
    "MESSAGING_KEY_PREFIX",
    "NOTIFICATIONS_CHANNEL",
]
